#ifndef PLUGINWEB_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(PLUGINWEB_LIBRARY)
#  define PLUGINBAIDU_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINBAIDU_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINLOGIN_GLOBAL_H


#define PLUGINBAIDU_GLOBAL_H